### ISSUE TITLE
Understanding the outcomes of Google Summer of Code

### ISSUE THREAD

**Issue by j3ffsilva** [alexjbest/alexjbest.github.io#2]
Dear Alex,

I am a Ph.D. student at the University of São Paulo (Brazil). We would like to understand how and how much Open Source Communities benefit from participating in Google Summer of Code (GSoC). We believe that your experience in GSoC is valuable and could help us achieve that. In a 1-minute questionnaire, we would like to know:

Concerning the project entitled "Implementing methods to find the Hermite normal form in FLINT" developed in GSoC 2014.

1. Do you have a GitHub repository for the GSoC project? If so, could you provide us with the link to the project?

2. Have you continued committing code or opening issues to the GSoC project after GSoC? (Yes / No) If so, code, issues or both?

3. Have you continued committing code or opening issues to other OSS projects after GSoC? (Yes / No) If so, code, issues or both?

4. Could we use aggregate data from your participation in GSoC and other OSS projects in our research?

The following link contains a sample of our work and how we would use your data:
https://ieeexplore.ieee.org/document/8094410/

Regards,

Jefferson

**Comment by alexjbest** [comment]
Hi Jefferson,

1.  https://github.com/alexjbest/flint2

2. Yes, both, maybe not official issues on github but I'm pretty sure I've mentioned some bugs.

3. Yes, both

4. Yes

Best wishes,

Alex

P.s. email might have been a  better way to contact, I almost missed this

**Comment by j3ffsilva** [comment]
Thanks for contributing to my research.

Best Regards,

Jefferson

Em ter, 4 de set de 2018 às 20:49, Alex J Best <notifications@github.com>
escreveu:
